### ISSUE TITLE
你好，请问这个有实时预览功能吗，可以在高版本chrome中跑吗

### ISSUE THREAD

**Issue by rmchen-12** [cc29sf3/hikvisionHLSdemo#1]
恩，如题，十分感谢！

**Comment by cc29sf3** [comment]
就是把视频流显示在浏览器中，看网络条件有大概十几秒的延迟，我用的应该是最近版本的chrome

在 2018-11-27 11:41:42，"panno" <notifications@github.com> 写道：


恩，如题，十分感谢！

**Comment by rmchen-12** [comment]
@cc29sf3 哈哈，谢谢大佬，我的也可以了
